### ISSUE TITLE
Missing tags with git describe

### ISSUE THREAD

**Issue by benhylau** [hamishcoleman/cjdns_tool#6]
`git describe` as used [here](https://github.com/hamishcoleman/cjdns_tool/blob/master/Makefile#L10) is giving me trouble when I have non-annotated tags. I wonder if this serves your purpose:

```
git describe --tags --long --dirty
```

The `--tags` does this:

```
--tags
Instead of using only the annotated tags, use any tag found in refs/tags namespace. This option enables matching a lightweight (non-annotated) tag.
```

**Comment by hamishcoleman** [comment]
Annotated tags are used for version releases to allow the version to have release notes attached to it.  This also distinguishes these tags from tags used as personal bookmarks.  Basically, this is working as designed.

Have you tried just using annotated tags for your use case?

**Comment by benhylau** [comment]
Using annotated tags will work. It's for another repo, and I generally don't attach notes to tags, but what you have works for you so I am closing this.

**Comment by hamishcoleman** [comment]
The annotated tags are not all about notes - they also have an author, a date and can be optionally signed - all of which are useful for proof of authorisation, legitimacy and consistency when releasing software.

If you are building packages, I strongly recommend you use annotated tags
